#!/bin/sh
# autopkgtest check: Run the installed-tests to verify glib works correctly
# (C) 2013 Canonical Ltd.
# Author: Iain Lane <iain.lane@canonical.com>

set -e

export XDG_RUNTIME_DIR=$ADTTMP

if [ -x /usr/bin/dbus-run-session ]; then
    dbus-run-session -- xvfb-run -a gnome-desktop-testing-runner glib
else
    dbus-launch --exit-with-session xvfb-run -a gnome-desktop-testing-runner glib
fi
